module.exports.locales = function(){
    return [
        { code : 'en-AS', name : 'American Samoa' },
        { code : 'en-AG', name : 'Antigua & Barbuda' },
        { code : 'en-AI', name : 'Anguilla' },
        { code : 'en-AT', name : 'Austria' },
        { code : 'en-AU', name : 'Australia' },
        { code : 'en-BB', name : 'Barbados' },
        { code : 'en-BE', name : 'Belgium' },
        { code : 'en-BI', name : 'Burundi' },
        { code : 'en-BM', name : 'Bermuda' },
        { code : 'en-BS', name : 'Bahamas' },
        { code : 'en-BW', name : 'Botswana' },
        { code : 'en-BZ', name : 'Belize' },
        { code : 'en-CA', name : 'Canada' },
        { code : 'en-CC', name : 'Cocos [Keeling] Islands' },
        { code : 'en-CK', name : 'Cook Islands' },
        { code : 'en-CM', name : 'Cameroon' },
        { code : 'en-CX', name : 'Christmas Island' },
        { code : 'en-CY', name : 'Cyprus' },
        { code : 'en-DE', name : 'Germany' },
        { code : 'en-DG', name : 'Diego Garcia' },
        { code : 'en-DK', name : 'Denmark' },
        { code : 'en-DM', name : 'Dominica' },
        { code : 'en-ER', name : 'Eritrea' },
        { code : 'en-FI', name : 'Finland' },
        { code : 'en-FJ', name : 'Fiji' },
        { code : 'en-FK', name : 'Falkland Islands' },
        { code : 'en-FM', name : 'Micronesia' },
        { code : 'en-GB', name : 'United Kingdom' },
        { code : 'en-US', name : 'United States' },
        { code : 'en-GD', name : 'Grenada' },
        { code : 'en-GG', name : 'Guernsey' },
        { code : 'en-GH', name : 'Ghana' },
        { code : 'en-GI', name : 'Gibraltar' },
        { code : 'en-GM', name : 'Gambia' },
        { code : 'en-GU', name : 'Guam' },
        { code : 'en-GY', name : 'Guyana' },
        { code : 'en-HK', name : 'Hong Kong SAR China' },
        { code : 'en-IE', name : 'Ireland' },
        { code : 'en-IL', name : 'Israel' },
        { code : 'en-IM', name : 'Isle of Man' },
        { code : 'en-IN', name : 'India' },
        { code : 'en-IO', name : 'British Indian Ocean Territory' },
        { code : 'en-JE', name : 'Jersey' },
        { code : 'en-JM', name : 'Jamaica' },
        { code : 'en-KE', name : 'Kenya' },
        { code : 'en-KI', name : 'Kiribati' },
        { code : 'en-KN', name : 'St. Kitts & Nevis' },
        { code : 'en-KY', name : 'Cayman Islands' },
        { code : 'en-LC', name : 'St. Lucia' },
        { code : 'en-LR', name : 'Liberia' },
        { code : 'en-LS', name : 'Lesotho' },
        { code : 'en-MG', name : 'Madagascar' },
        { code : 'en-MH', name : 'Marshall Islands' },
        { code : 'en-MO', name : 'Macau SAR China' },
        { code : 'en-MP', name : 'Northern Mariana Islands' },
        { code : 'en-MS', name : 'Montserrat' },
        { code : 'en-MT', name : 'Malta' },
        { code : 'en-MU', name : 'Mauritius' },
        { code : 'en-MW', name : 'Malawi' },
        { code : 'en-MY', name : 'Malaysia' },
        { code : 'en-NA', name : 'Namibia' },
        { code : 'en-NF', name : 'Norfolk Island' },
        { code : 'en-NG', name : 'Nigeria' },
        { code : 'en-NL', name : 'Netherlands' },
        { code : 'en-NR', name : 'Nauru' },
        { code : 'en-NU', name : 'Niue' },
        { code : 'en-NZ', name : 'New Zealand' },
        { code : 'en-PG', name : 'Papua New Guinea' },
        { code : 'en-PH', name : 'Philippines' },
        { code : 'en-PK', name : 'Pakistan' },
        { code : 'en-PN', name : 'Pitcairn Islands' },
        { code : 'en-PR', name : 'Puerto Rico' },
        { code : 'en-PW', name : 'Palau' },
        { code : 'en-RW', name : 'Rwanda' },
        { code : 'en-SB', name : 'Solomon Islands' },
        { code : 'en-SC', name : 'Seychelles' },
        { code : 'en-SD', name : 'Sudan' },
        { code : 'en-SE', name : 'Sweden' },
        { code : 'en-CH', name : 'Switzerland' },
        { code : 'en-SG', name : 'Singapore' },
        { code : 'en-SH', name : 'St. Helena' },
        { code : 'en-SI', name : 'Slovenia' },
        { code : 'en-SL', name : 'Sierra Leone' },
        { code : 'en-SS', name : 'South Sudan' },
        { code : 'en-SX', name : 'Sint Maarten' },
        { code : 'en-SZ', name : 'Swaziland' },
        { code : 'en-TC', name : 'Turks & Caicos Islands' },
        { code : 'en-TK', name : 'Tokelau' },
        { code : 'en-TO', name : 'Tonga' },
        { code : 'en-TT', name : 'Trinidad & Tobago' },
        { code : 'en-TV', name : 'Tuvalu' },
        { code : 'en-TZ', name : 'Tanzania' },
        { code : 'en-UG', name : 'Uganda' },
        { code : 'en-UM', name : 'U.S. Outlying Islands' },
        { code : 'en-VC', name : 'St. Vincent & Grenadines' },
        { code : 'en-VG', name : 'British Virgin Islands' },
        { code : 'en-VI', name : 'U.S. Virgin Islands' },
        { code : 'en-VU', name : 'Vanuatu' },
        { code : 'en-WS', name : 'Samoa' },
        { code : 'en-ZA', name : 'South Africa' },
        { code : 'en-ZM', name : 'Zambia' },
        { code : 'en-ZW', name : 'Zimbabwe' },
    ];    
};

module.exports.timeZones = function(){
    return [
        { id : 'Pacific/Niue', name : '(UTC-11:00) Niue' },
        { id : 'Pacific/Midway', name : '(UTC-11:00) Midway' },
        { id : 'Pacific/Pago_Pago', name : '(UTC-11:00) Pago_Pago' },
        { id : 'Pacific/Rarotonga', name : '(UTC-10:00) Rarotonga' },
        { id : 'Pacific/Honolulu', name : '(UTC-10:00) Honolulu' },
        { id : 'America/Adak', name : '(UTC-10:00) Adak' },
        { id : 'Pacific/Tahiti', name : '(UTC-10:00) Tahiti' },
        { id : 'Pacific/Marquesas', name : '(UTC-09:30) Marquesas' },
        { id : 'America/Nome', name : '(UTC-09:00) Nome' },
        { id : 'America/Anchorage', name : '(UTC-09:00) Anchorage' },
        { id : 'America/Juneau', name : '(UTC-09:00) Juneau' },
        { id : 'America/Metlakatla', name : '(UTC-09:00) Metlakatla' },
        { id : 'America/Yakutat', name : '(UTC-09:00) Yakutat' },
        { id : 'America/Sitka', name : '(UTC-09:00) Sitka' },
        { id : 'Pacific/Gambier', name : '(UTC-09:00) Gambier' },
        { id : 'America/Vancouver', name : '(UTC-08:00) Vancouver' },
        { id : 'America/Los_Angeles', name : '(UTC-08:00) Los_Angeles' },
        { id : 'America/Tijuana', name : '(UTC-08:00) Tijuana' },
        { id : 'Pacific/Pitcairn', name : '(UTC-08:00) Pitcairn' },
        { id : 'America/Hermosillo', name : '(UTC-07:00) Hermosillo' },
        { id : 'America/Chihuahua', name : '(UTC-07:00) Chihuahua' },
        { id : 'America/Mazatlan', name : '(UTC-07:00) Mazatlan' },
        { id : 'America/Boise', name : '(UTC-07:00) Boise' },
        { id : 'America/Denver', name : '(UTC-07:00) Denver' },
        { id : 'America/Dawson_Creek', name : '(UTC-07:00) Dawson_Creek' },
        { id : 'America/Phoenix', name : '(UTC-07:00) Phoenix' },
        { id : 'America/Fort_Nelson', name : '(UTC-07:00) Fort_Nelson' },
        { id : 'America/Ojinaga', name : '(UTC-07:00) Ojinaga' },
        { id : 'America/Yellowknife', name : '(UTC-07:00) Yellowknife' },
        { id : 'America/Creston', name : '(UTC-07:00) Creston' },
        { id : 'America/Inuvik', name : '(UTC-07:00) Inuvik' },
        { id : 'America/Edmonton', name : '(UTC-07:00) Edmonton' },
        { id : 'America/Cambridge_Bay', name : '(UTC-07:00) Cambridge_Bay' },
        { id : 'America/Dawson', name : '(UTC-07:00) Dawson' },
        { id : 'America/Whitehorse', name : '(UTC-07:00) Whitehorse' },
        { id : 'America/Indiana/Tell_City', name : '(UTC-06:00) Tell_City' },
        { id : 'America/Guatemala', name : '(UTC-06:00) Guatemala' },
        { id : 'America/Regina', name : '(UTC-06:00) Regina' },
        { id : 'America/Indiana/Knox', name : '(UTC-06:00) Knox' },
        { id : 'America/Mexico_City', name : '(UTC-06:00) Mexico_City' },
        { id : 'America/Belize', name : '(UTC-06:00) Belize' },
        { id : 'America/El_Salvador', name : '(UTC-06:00) El_Salvador' },
        { id : 'America/Chicago', name : '(UTC-06:00) Chicago' },
        { id : 'America/Tegucigalpa', name : '(UTC-06:00) Tegucigalpa' },
        { id : 'America/North_Dakota/New_Salem', name : '(UTC-06:00) New_Salem' },
        { id : 'America/North_Dakota/Center', name : '(UTC-06:00) Center' },
        { id : 'America/Rankin_Inlet', name : '(UTC-06:00) Rankin_Inlet' },
        { id : 'America/North_Dakota/Beulah', name : '(UTC-06:00) Beulah' },
        { id : 'America/Merida', name : '(UTC-06:00) Merida' },
        { id : 'America/Monterrey', name : '(UTC-06:00) Monterrey' },
        { id : 'America/Matamoros', name : '(UTC-06:00) Matamoros' },
        { id : 'America/Bahia_Banderas', name : '(UTC-06:00) Bahia_Banderas' },
        { id : 'America/Winnipeg', name : '(UTC-06:00) Winnipeg' },
        { id : 'America/Managua', name : '(UTC-06:00) Managua' },
        { id : 'America/Rainy_River', name : '(UTC-06:00) Rainy_River' },
        { id : 'America/Swift_Current', name : '(UTC-06:00) Swift_Current' },
        { id : 'America/Resolute', name : '(UTC-06:00) Resolute' },
        { id : 'America/Menominee', name : '(UTC-06:00) Menominee' },
        { id : 'America/Costa_Rica', name : '(UTC-06:00) Costa_Rica' },
        { id : 'Pacific/Easter', name : '(UTC-06:00) Easter' },
        { id : 'Pacific/Galapagos', name : '(UTC-06:00) Galapagos' },
        { id : 'America/Rio_Branco', name : '(UTC-05:00) Rio_Branco' },
        { id : 'America/Eirunepe', name : '(UTC-05:00) Eirunepe' },
        { id : 'America/Bogota', name : '(UTC-05:00) Bogota' },
        { id : 'America/Havana', name : '(UTC-05:00) Havana' },
        { id : 'America/Indiana/Winamac', name : '(UTC-05:00) Winamac' },
        { id : 'America/Detroit', name : '(UTC-05:00) Detroit' },
        { id : 'America/Kentucky/Louisville', name : '(UTC-05:00) Louisville' },
        { id : 'America/Toronto', name : '(UTC-05:00) Toronto' },
        { id : 'America/Nipigon', name : '(UTC-05:00) Nipigon' },
        { id : 'America/Thunder_Bay', name : '(UTC-05:00) Thunder_Bay' },
        { id : 'America/Iqaluit', name : '(UTC-05:00) Iqaluit' },
        { id : 'America/Pangnirtung', name : '(UTC-05:00) Pangnirtung' },
        { id : 'America/Atikokan', name : '(UTC-05:00) Atikokan' },
        { id : 'America/Port-au-Prince', name : '(UTC-05:00) Port-au-Prince' },
        { id : 'America/Jamaica', name : '(UTC-05:00) Jamaica' },
        { id : 'America/Panama', name : '(UTC-05:00) Panama' },
        { id : 'America/Cayman', name : '(UTC-05:00) Cayman' },
        { id : 'America/Cancun', name : '(UTC-05:00) Cancun' },
        { id : 'America/Indiana/Marengo', name : '(UTC-05:00) Marengo' },
        { id : 'America/Kentucky/Monticello', name : '(UTC-05:00) Monticello' },
        { id : 'America/Indiana/Petersburg', name : '(UTC-05:00) Petersburg' },
        { id : 'America/Indiana/Vincennes', name : '(UTC-05:00) Vincennes' },
        { id : 'America/Indiana/Indianapolis', name : '(UTC-05:00) Indianapolis' },
        { id : 'America/New_York', name : '(UTC-05:00) New_York' },
        { id : 'America/Grand_Turk', name : '(UTC-05:00) Grand_Turk' },
        { id : 'America/Indiana/Vevay', name : '(UTC-05:00) Vevay' },
        { id : 'America/Nassau', name : '(UTC-05:00) Nassau' },
        { id : 'America/Guayaquil', name : '(UTC-05:00) Guayaquil' },
        { id : 'America/Lima', name : '(UTC-05:00) Lima' },
        { id : 'America/Porto_Velho', name : '(UTC-04:00) Porto_Velho' },
        { id : 'America/Manaus', name : '(UTC-04:00) Manaus' },
        { id : 'America/Cuiaba', name : '(UTC-04:00) Cuiaba' },
        { id : 'America/Campo_Grande', name : '(UTC-04:00) Campo_Grande' },
        { id : 'America/Boa_Vista', name : '(UTC-04:00) Boa_Vista' },
        { id : 'America/Montserrat', name : '(UTC-04:00) Montserrat' },
        { id : 'America/Marigot', name : '(UTC-04:00) Marigot' },
        { id : 'America/St_Lucia', name : '(UTC-04:00) St_Lucia' },
        { id : 'America/Santo_Domingo', name : '(UTC-04:00) Santo_Domingo' },
        { id : 'America/St_Kitts', name : '(UTC-04:00) St_Kitts' },
        { id : 'America/Puerto_Rico', name : '(UTC-04:00) Puerto_Rico' },
        { id : 'America/Port_of_Spain', name : '(UTC-04:00) Port_of_Spain' },
        { id : 'America/Curacao', name : '(UTC-04:00) Curacao' },
        { id : 'America/Lower_Princes', name : '(UTC-04:00) Lower_Princes' },
        { id : 'America/Guadeloupe', name : '(UTC-04:00) Guadeloupe' },
        { id : 'America/Thule', name : '(UTC-04:00) Thule' },
        { id : 'America/Dominica', name : '(UTC-04:00) Dominica' },
        { id : 'America/Grenada', name : '(UTC-04:00) Grenada' },
        { id : 'America/Martinique', name : '(UTC-04:00) Martinique' },
        { id : 'America/Goose_Bay', name : '(UTC-04:00) Goose_Bay' },
        { id : 'America/Kralendijk', name : '(UTC-04:00) Kralendijk' },
        { id : 'Atlantic/Bermuda', name : '(UTC-04:00) Bermuda' },
        { id : 'America/St_Barthelemy', name : '(UTC-04:00) St_Barthelemy' },
        { id : 'America/Aruba', name : '(UTC-04:00) Aruba' },
        { id : 'America/St_Vincent', name : '(UTC-04:00) St_Vincent' },
        { id : 'America/Barbados', name : '(UTC-04:00) Barbados' },
        { id : 'America/Blanc-Sablon', name : '(UTC-04:00) Blanc-Sablon' },
        { id : 'America/Antigua', name : '(UTC-04:00) Antigua' },
        { id : 'America/Tortola', name : '(UTC-04:00) Tortola' },
        { id : 'America/Moncton', name : '(UTC-04:00) Moncton' },
        { id : 'America/Halifax', name : '(UTC-04:00) Halifax' },
        { id : 'America/Anguilla', name : '(UTC-04:00) Anguilla' },
        { id : 'America/Glace_Bay', name : '(UTC-04:00) Glace_Bay' },
        { id : 'America/St_Thomas', name : '(UTC-04:00) St_Thomas' },
        { id : 'America/La_Paz', name : '(UTC-04:00) La_Paz' },
        { id : 'America/Santiago', name : '(UTC-04:00) Santiago' },
        { id : 'America/Guyana', name : '(UTC-04:00) Guyana' },
        { id : 'America/Asuncion', name : '(UTC-04:00) Asuncion' },
        { id : 'America/Caracas', name : '(UTC-04:00) Caracas' },
        { id : 'America/St_Johns', name : '(UTC-03:30) St_Johns' },
        { id : 'America/Argentina/Ushuaia', name : '(UTC-03:00) Ushuaia' },
        { id : 'America/Argentina/Mendoza', name : '(UTC-03:00) Mendoza' },
        { id : 'America/Argentina/Rio_Gallegos', name : '(UTC-03:00) Rio_Gallegos' },
        { id : 'America/Argentina/La_Rioja', name : '(UTC-03:00) La_Rioja' },
        { id : 'America/Argentina/San_Juan', name : '(UTC-03:00) San_Juan' },
        { id : 'America/Argentina/Catamarca', name : '(UTC-03:00) Catamarca' },
        { id : 'America/Argentina/Salta', name : '(UTC-03:00) Salta' },
        { id : 'America/Argentina/Jujuy', name : '(UTC-03:00) Jujuy' },
        { id : 'America/Argentina/Cordoba', name : '(UTC-03:00) Cordoba' },
        { id : 'America/Argentina/Buenos_Aires', name : '(UTC-03:00) Buenos_Aires' },
        { id : 'America/Argentina/Tucuman', name : '(UTC-03:00) Tucuman' },
        { id : 'America/Belem', name : '(UTC-03:00) Belem' },
        { id : 'America/Santarem', name : '(UTC-03:00) Santarem' },
        { id : 'America/Sao_Paulo', name : '(UTC-03:00) Sao_Paulo' },
        { id : 'America/Fortaleza', name : '(UTC-03:00) Fortaleza' },
        { id : 'America/Recife', name : '(UTC-03:00) Recife' },
        { id : 'America/Bahia', name : '(UTC-03:00) Bahia' },
        { id : 'America/Maceio', name : '(UTC-03:00) Maceio' },
        { id : 'America/Araguaina', name : '(UTC-03:00) Araguaina' },
        { id : 'Atlantic/Stanley', name : '(UTC-03:00) Stanley' },
        { id : 'America/Cayenne', name : '(UTC-03:00) Cayenne' },
        { id : 'America/Nuuk', name : '(UTC-03:00) Nuuk' },
        { id : 'Antarctica/Palmer', name : '(UTC-03:00) Palmer' },
        { id : 'America/Punta_Arenas', name : '(UTC-03:00) Punta_Arenas' },
        { id : 'Antarctica/Rothera', name : '(UTC-03:00) Rothera' },
        { id : 'America/Miquelon', name : '(UTC-03:00) Miquelon' },
        { id : 'America/Paramaribo', name : '(UTC-03:00) Paramaribo' },
        { id : 'America/Montevideo', name : '(UTC-03:00) Montevideo' },
        { id : 'America/Argentina/San_Luis', name : '(UTC-03:00) San_Luis' },
        { id : 'America/Noronha', name : '(UTC-02:00) Noronha' },
        { id : 'Atlantic/South_Georgia', name : '(UTC-02:00) South_Georgia' },
        { id : 'Atlantic/Azores', name : '(UTC-01:00) Azores' },
        { id : 'Atlantic/Cape_Verde', name : '(UTC-01:00) Cape_Verde' },
        { id : 'America/Scoresbysund', name : '(UTC-01:00) Scoresbysund' },
        { id : 'UTC', name : '(UTC) UTC' },
        { id : 'Africa/Bamako', name : '(UTC+00:00) Bamako' },
        { id : 'Africa/Monrovia', name : '(UTC+00:00) Monrovia' },
        { id : 'Antarctica/Troll', name : '(UTC+00:00) Troll' },
        { id : 'Africa/Lome', name : '(UTC+00:00) Lome' },
        { id : 'Africa/Freetown', name : '(UTC+00:00) Freetown' },
        { id : 'Europe/London', name : '(UTC+00:00) London' },
        { id : 'Europe/Jersey', name : '(UTC+00:00) Jersey' },
        { id : 'Atlantic/Reykjavik', name : '(UTC+00:00) Reykjavik' },
        { id : 'Africa/Sao_Tome', name : '(UTC+00:00) Sao_Tome' },
        { id : 'Europe/Isle_of_Man', name : '(UTC+00:00) Isle_of_Man' },
        { id : 'Africa/Nouakchott', name : '(UTC+00:00) Nouakchott' },
        { id : 'Africa/Dakar', name : '(UTC+00:00) Dakar' },
        { id : 'Africa/Abidjan', name : '(UTC+00:00) Abidjan' },
        { id : 'Africa/Bissau', name : '(UTC+00:00) Bissau' },
        { id : 'Africa/Ouagadougou', name : '(UTC+00:00) Ouagadougou' },
        { id : 'Atlantic/St_Helena', name : '(UTC+00:00) St_Helena' },
        { id : 'America/Danmarkshavn', name : '(UTC+00:00) Danmarkshavn' },
        { id : 'Africa/Banjul', name : '(UTC+00:00) Banjul' },
        { id : 'Africa/Conakry', name : '(UTC+00:00) Conakry' },
        { id : 'Europe/Guernsey', name : '(UTC+00:00) Guernsey' },
        { id : 'Africa/Accra', name : '(UTC+00:00) Accra' },
        { id : 'Atlantic/Madeira', name : '(UTC+00:00) Madeira' },
        { id : 'Atlantic/Canary', name : '(UTC+00:00) Canary' },
        { id : 'Atlantic/Faroe', name : '(UTC+00:00) Faroe' },
        { id : 'Europe/Lisbon', name : '(UTC+00:00) Lisbon' },
        { id : 'Europe/Prague', name : '(UTC+01:00) Prague' },
        { id : 'Europe/Paris', name : '(UTC+01:00) Paris' },
        { id : 'Africa/Tunis', name : '(UTC+01:00) Tunis' },
        { id : 'Europe/Gibraltar', name : '(UTC+01:00) Gibraltar' },
        { id : 'Europe/Vatican', name : '(UTC+01:00) Vatican' },
        { id : 'Europe/Sarajevo', name : '(UTC+01:00) Sarajevo' },
        { id : 'Europe/Vaduz', name : '(UTC+01:00) Vaduz' },
        { id : 'Europe/Tirane', name : '(UTC+01:00) Tirane' },
        { id : 'Europe/Zurich', name : '(UTC+01:00) Zurich' },
        { id : 'Europe/Luxembourg', name : '(UTC+01:00) Luxembourg' },
        { id : 'Europe/Monaco', name : '(UTC+01:00) Monaco' },
        { id : 'Europe/Podgorica', name : '(UTC+01:00) Podgorica' },
        { id : 'Europe/Malta', name : '(UTC+01:00) Malta' },
        { id : 'Europe/Andorra', name : '(UTC+01:00) Andorra' },
        { id : 'Arctic/Longyearbyen', name : '(UTC+01:00) Longyearbyen' },
        { id : 'Europe/Skopje', name : '(UTC+01:00) Skopje' },
        { id : 'Europe/Berlin', name : '(UTC+01:00) Berlin' },
        { id : 'Europe/Oslo', name : '(UTC+01:00) Oslo' },
        { id : 'Europe/Amsterdam', name : '(UTC+01:00) Amsterdam' },
        { id : 'Europe/Warsaw', name : '(UTC+01:00) Warsaw' },
        { id : 'Europe/Copenhagen', name : '(UTC+01:00) Copenhagen' },
        { id : 'Africa/Algiers', name : '(UTC+01:00) Algiers' },
        { id : 'Europe/Stockholm', name : '(UTC+01:00) Stockholm' },
        { id : 'Europe/San_Marino', name : '(UTC+01:00) San_Marino' },
        { id : 'Europe/Zagreb', name : '(UTC+01:00) Zagreb' },
        { id : 'Europe/Vienna', name : '(UTC+01:00) Vienna' },
        { id : 'Europe/Budapest', name : '(UTC+01:00) Budapest' },
        { id : 'Europe/Belgrade', name : '(UTC+01:00) Belgrade' },
        { id : 'Europe/Brussels', name : '(UTC+01:00) Brussels' },
        { id : 'Europe/Madrid', name : '(UTC+01:00) Madrid' },
        { id : 'Africa/Ceuta', name : '(UTC+01:00) Ceuta' },
        { id : 'Europe/Bratislava', name : '(UTC+01:00) Bratislava' },
        { id : 'Europe/Rome', name : '(UTC+01:00) Rome' },
        { id : 'Europe/Busingen', name : '(UTC+01:00) Busingen' },
        { id : 'Europe/Ljubljana', name : '(UTC+01:00) Ljubljana' },
        { id : 'Europe/Dublin', name : '(UTC+01:00) Dublin' },
        { id : 'Africa/Malabo', name : '(UTC+01:00) Malabo' },
        { id : 'Africa/Lagos', name : '(UTC+01:00) Lagos' },
        { id : 'Africa/Porto-Novo', name : '(UTC+01:00) Porto-Novo' },
        { id : 'Africa/Niamey', name : '(UTC+01:00) Niamey' },
        { id : 'Africa/Kinshasa', name : '(UTC+01:00) Kinshasa' },
        { id : 'Africa/Luanda', name : '(UTC+01:00) Luanda' },
        { id : 'Africa/Ndjamena', name : '(UTC+01:00) Ndjamena' },
        { id : 'Africa/Brazzaville', name : '(UTC+01:00) Brazzaville' },
        { id : 'Africa/Douala', name : '(UTC+01:00) Douala' },
        { id : 'Africa/Libreville', name : '(UTC+01:00) Libreville' },
        { id : 'Africa/Bangui', name : '(UTC+01:00) Bangui' },
        { id : 'Africa/Casablanca', name : '(UTC+01:00) Casablanca' },
        { id : 'Africa/El_Aaiun', name : '(UTC+01:00) El_Aaiun' },
        { id : 'Africa/Blantyre', name : '(UTC+02:00) Blantyre' },
        { id : 'Africa/Windhoek', name : '(UTC+02:00) Windhoek' },
        { id : 'Africa/Kigali', name : '(UTC+02:00) Kigali' },
        { id : 'Africa/Maputo', name : '(UTC+02:00) Maputo' },
        { id : 'Africa/Khartoum', name : '(UTC+02:00) Khartoum' },
        { id : 'Africa/Harare', name : '(UTC+02:00) Harare' },
        { id : 'Africa/Bujumbura', name : '(UTC+02:00) Bujumbura' },
        { id : 'Africa/Lusaka', name : '(UTC+02:00) Lusaka' },
        { id : 'Africa/Gaborone', name : '(UTC+02:00) Gaborone' },
        { id : 'Africa/Lubumbashi', name : '(UTC+02:00) Lubumbashi' },
        { id : 'Africa/Juba', name : '(UTC+02:00) Juba' },
        { id : 'Asia/Gaza', name : '(UTC+02:00) Gaza' },
        { id : 'Asia/Hebron', name : '(UTC+02:00) Hebron' },
        { id : 'Europe/Bucharest', name : '(UTC+02:00) Bucharest' },
        { id : 'Europe/Mariehamn', name : '(UTC+02:00) Mariehamn' },
        { id : 'Europe/Sofia', name : '(UTC+02:00) Sofia' },
        { id : 'Europe/Athens', name : '(UTC+02:00) Athens' },
        { id : 'Europe/Helsinki', name : '(UTC+02:00) Helsinki' },
        { id : 'Asia/Amman', name : '(UTC+02:00) Amman' },
        { id : 'Africa/Cairo', name : '(UTC+02:00) Cairo' },
        { id : 'Asia/Damascus', name : '(UTC+02:00) Damascus' },
        { id : 'Asia/Beirut', name : '(UTC+02:00) Beirut' },
        { id : 'Europe/Kaliningrad', name : '(UTC+02:00) Kaliningrad' },
        { id : 'Europe/Vilnius', name : '(UTC+02:00) Vilnius' },
        { id : 'Europe/Kiev', name : '(UTC+02:00) Kiev' },
        { id : 'Europe/Riga', name : '(UTC+02:00) Riga' },
        { id : 'Africa/Tripoli', name : '(UTC+02:00) Tripoli' },
        { id : 'Europe/Uzhgorod', name : '(UTC+02:00) Uzhgorod' },
        { id : 'Europe/Chisinau', name : '(UTC+02:00) Chisinau' },
        { id : 'Europe/Tallinn', name : '(UTC+02:00) Tallinn' },
        { id : 'Asia/Nicosia', name : '(UTC+02:00) Nicosia' },
        { id : 'Europe/Zaporozhye', name : '(UTC+02:00) Zaporozhye' },
        { id : 'Asia/Famagusta', name : '(UTC+02:00) Famagusta' },
        { id : 'Asia/Jerusalem', name : '(UTC+02:00) Jerusalem' },
        { id : 'Africa/Maseru', name : '(UTC+02:00) Maseru' },
        { id : 'Africa/Johannesburg', name : '(UTC+02:00) Johannesburg' },
        { id : 'Africa/Mbabane', name : '(UTC+02:00) Mbabane' },
        { id : 'Asia/Baghdad', name : '(UTC+03:00) Baghdad' },
        { id : 'Asia/Qatar', name : '(UTC+03:00) Qatar' },
        { id : 'Asia/Kuwait', name : '(UTC+03:00) Kuwait' },
        { id : 'Asia/Aden', name : '(UTC+03:00) Aden' },
        { id : 'Asia/Riyadh', name : '(UTC+03:00) Riyadh' },
        { id : 'Asia/Bahrain', name : '(UTC+03:00) Bahrain' },
        { id : 'Africa/Djibouti', name : '(UTC+03:00) Djibouti' },
        { id : 'Africa/Kampala', name : '(UTC+03:00) Kampala' },
        { id : 'Africa/Mogadishu', name : '(UTC+03:00) Mogadishu' },
        { id : 'Africa/Addis_Ababa', name : '(UTC+03:00) Addis_Ababa' },
        { id : 'Africa/Asmara', name : '(UTC+03:00) Asmara' },
        { id : 'Africa/Nairobi', name : '(UTC+03:00) Nairobi' },
        { id : 'Africa/Dar_es_Salaam', name : '(UTC+03:00) Dar_es_Salaam' },
        { id : 'Indian/Comoro', name : '(UTC+03:00) Comoro' },
        { id : 'Indian/Mayotte', name : '(UTC+03:00) Mayotte' },
        { id : 'Indian/Antananarivo', name : '(UTC+03:00) Antananarivo' },
        { id : 'Europe/Istanbul', name : '(UTC+03:00) Istanbul' },
        { id : 'Europe/Kirov', name : '(UTC+03:00) Kirov' },
        { id : 'Europe/Minsk', name : '(UTC+03:00) Minsk' },
        { id : 'Europe/Volgograd', name : '(UTC+03:00) Volgograd' },
        { id : 'Europe/Simferopol', name : '(UTC+03:00) Simferopol' },
        { id : 'Europe/Moscow', name : '(UTC+03:00) Moscow' },
        { id : 'Antarctica/Syowa', name : '(UTC+03:00) Syowa' },
        { id : 'Asia/Tehran', name : '(UTC+03:30) Tehran' },
        { id : 'Asia/Yerevan', name : '(UTC+04:00) Yerevan' },
        { id : 'Asia/Baku', name : '(UTC+04:00) Baku' },
        { id : 'Europe/Ulyanovsk', name : '(UTC+04:00) Ulyanovsk' },
        { id : 'Europe/Saratov', name : '(UTC+04:00) Saratov' },
        { id : 'Europe/Astrakhan', name : '(UTC+04:00) Astrakhan' },
        { id : 'Asia/Tbilisi', name : '(UTC+04:00) Tbilisi' },
        { id : 'Asia/Dubai', name : '(UTC+04:00) Dubai' },
        { id : 'Asia/Muscat', name : '(UTC+04:00) Muscat' },
        { id : 'Indian/Mauritius', name : '(UTC+04:00) Mauritius' },
        { id : 'Indian/Reunion', name : '(UTC+04:00) Reunion' },
        { id : 'Europe/Samara', name : '(UTC+04:00) Samara' },
        { id : 'Indian/Mahe', name : '(UTC+04:00) Mahe' },
        { id : 'Asia/Kabul', name : '(UTC+04:30) Kabul' },
        { id : 'Asia/Qyzylorda', name : '(UTC+05:00) Qyzylorda' },
        { id : 'Indian/Kerguelen', name : '(UTC+05:00) Kerguelen' },
        { id : 'Indian/Maldives', name : '(UTC+05:00) Maldives' },
        { id : 'Antarctica/Mawson', name : '(UTC+05:00) Mawson' },
        { id : 'Asia/Karachi', name : '(UTC+05:00) Karachi' },
        { id : 'Asia/Dushanbe', name : '(UTC+05:00) Dushanbe' },
        { id : 'Asia/Ashgabat', name : '(UTC+05:00) Ashgabat' },
        { id : 'Asia/Tashkent', name : '(UTC+05:00) Tashkent' },
        { id : 'Asia/Samarkand', name : '(UTC+05:00) Samarkand' },
        { id : 'Asia/Aqtau', name : '(UTC+05:00) Aqtau' },
        { id : 'Asia/Atyrau', name : '(UTC+05:00) Atyrau' },
        { id : 'Asia/Oral', name : '(UTC+05:00) Oral' },
        { id : 'Asia/Aqtobe', name : '(UTC+05:00) Aqtobe' },
        { id : 'Asia/Yekaterinburg', name : '(UTC+05:00) Yekaterinburg' },
        { id : 'Asia/Colombo', name : '(UTC+05:30) Colombo' },
        { id : 'Asia/Kolkata', name : '(UTC+05:30) Kolkata' },
        { id : 'Asia/Kathmandu', name : '(UTC+05:45) Kathmandu' },
        { id : 'Asia/Dhaka', name : '(UTC+06:00) Dhaka' },
        { id : 'Asia/Thimphu', name : '(UTC+06:00) Thimphu' },
        { id : 'Asia/Almaty', name : '(UTC+06:00) Almaty' },
        { id : 'Asia/Qostanay', name : '(UTC+06:00) Qostanay' },
        { id : 'Asia/Urumqi', name : '(UTC+06:00) Urumqi' },
        { id : 'Indian/Chagos', name : '(UTC+06:00) Chagos' },
        { id : 'Asia/Bishkek', name : '(UTC+06:00) Bishkek' },
        { id : 'Asia/Omsk', name : '(UTC+06:00) Omsk' },
        { id : 'Antarctica/Vostok', name : '(UTC+06:00) Vostok' },
        { id : 'Indian/Cocos', name : '(UTC+06:30) Cocos' },
        { id : 'Asia/Yangon', name : '(UTC+06:30) Yangon' },
        { id : 'Indian/Christmas', name : '(UTC+07:00) Christmas' },
        { id : 'Antarctica/Davis', name : '(UTC+07:00) Davis' },
        { id : 'Asia/Barnaul', name : '(UTC+07:00) Barnaul' },
        { id : 'Asia/Tomsk', name : '(UTC+07:00) Tomsk' },
        { id : 'Asia/Hovd', name : '(UTC+07:00) Hovd' },
        { id : 'Asia/Phnom_Penh', name : '(UTC+07:00) Phnom_Penh' },
        { id : 'Asia/Bangkok', name : '(UTC+07:00) Bangkok' },
        { id : 'Asia/Vientiane', name : '(UTC+07:00) Vientiane' },
        { id : 'Asia/Ho_Chi_Minh', name : '(UTC+07:00) Ho_Chi_Minh' },
        { id : 'Asia/Novokuznetsk', name : '(UTC+07:00) Novokuznetsk' },
        { id : 'Asia/Krasnoyarsk', name : '(UTC+07:00) Krasnoyarsk' },
        { id : 'Asia/Novosibirsk', name : '(UTC+07:00) Novosibirsk' },
        { id : 'Asia/Jakarta', name : '(UTC+07:00) Jakarta' },
        { id : 'Asia/Pontianak', name : '(UTC+07:00) Pontianak' },
        { id : 'Australia/Perth', name : '(UTC+08:00) Perth' },
        { id : 'Asia/Brunei', name : '(UTC+08:00) Brunei' },
        { id : 'Asia/Makassar', name : '(UTC+08:00) Makassar' },
        { id : 'Asia/Shanghai', name : '(UTC+08:00) Shanghai' },
        { id : 'Asia/Macau', name : '(UTC+08:00) Macau' },
        { id : 'Asia/Choibalsan', name : '(UTC+08:00) Choibalsan' },
        { id : 'Asia/Hong_Kong', name : '(UTC+08:00) Hong_Kong' },
        { id : 'Asia/Irkutsk', name : '(UTC+08:00) Irkutsk' },
        { id : 'Asia/Kuala_Lumpur', name : '(UTC+08:00) Kuala_Lumpur' },
        { id : 'Asia/Kuching', name : '(UTC+08:00) Kuching' },
        { id : 'Asia/Manila', name : '(UTC+08:00) Manila' },
        { id : 'Asia/Singapore', name : '(UTC+08:00) Singapore' },
        { id : 'Asia/Taipei', name : '(UTC+08:00) Taipei' },
        { id : 'Asia/Ulaanbaatar', name : '(UTC+08:00) Ulaanbaatar' },
        { id : 'Australia/Eucla', name : '(UTC+08:45) Eucla' },
        { id : 'Asia/Dili', name : '(UTC+09:00) Dili' },
        { id : 'Asia/Jayapura', name : '(UTC+09:00) Jayapura' },
        { id : 'Asia/Tokyo', name : '(UTC+09:00) Tokyo' },
        { id : 'Asia/Seoul', name : '(UTC+09:00) Seoul' },
        { id : 'Pacific/Palau', name : '(UTC+09:00) Palau' },
        { id : 'Asia/Pyongyang', name : '(UTC+09:00) Pyongyang' },
        { id : 'Asia/Yakutsk', name : '(UTC+09:00) Yakutsk' },
        { id : 'Asia/Chita', name : '(UTC+09:00) Chita' },
        { id : 'Asia/Khandyga', name : '(UTC+09:00) Khandyga' },
        { id : 'Australia/Broken_Hill', name : '(UTC+09:30) Broken_Hill' },
        { id : 'Australia/Adelaide', name : '(UTC+09:30) Adelaide' },
        { id : 'Australia/Darwin', name : '(UTC+09:30) Darwin' },
        { id : 'Australia/Hobart', name : '(UTC+10:00) Hobart' },
        { id : 'Australia/Melbourne', name : '(UTC+10:00) Melbourne' },
        { id : 'Australia/Brisbane', name : '(UTC+10:00) Brisbane' },
        { id : 'Australia/Lindeman', name : '(UTC+10:00) Lindeman' },
        { id : 'Australia/Sydney', name : '(UTC+10:00) Sydney' },
        { id : 'Pacific/Saipan', name : '(UTC+10:00) Saipan' },
        { id : 'Pacific/Guam', name : '(UTC+10:00) Guam' },
        { id : 'Pacific/Chuuk', name : '(UTC+10:00) Chuuk' },
        { id : 'Antarctica/DumontDUrville', name : '(UTC+10:00) DumontDUrville' },
        { id : 'Antarctica/Macquarie', name : '(UTC+10:00) Macquarie' },
        { id : 'Pacific/Port_Moresby', name : '(UTC+10:00) Port_Moresby' },
        { id : 'Asia/Ust-Nera', name : '(UTC+10:00) Ust-Nera' },
        { id : 'Asia/Vladivostok', name : '(UTC+10:00) Vladivostok' },
        { id : 'Australia/Lord_Howe', name : '(UTC+10:30) Lord_Howe' },
        { id : 'Antarctica/Casey', name : '(UTC+11:00) Casey' },
        { id : 'Asia/Srednekolymsk', name : '(UTC+11:00) Srednekolymsk' },
        { id : 'Pacific/Bougainville', name : '(UTC+11:00) Bougainville' },
        { id : 'Pacific/Kosrae', name : '(UTC+11:00) Kosrae' },
        { id : 'Asia/Magadan', name : '(UTC+11:00) Magadan' },
        { id : 'Pacific/Noumea', name : '(UTC+11:00) Noumea' },
        { id : 'Pacific/Norfolk', name : '(UTC+11:00) Norfolk' },
        { id : 'Pacific/Pohnpei', name : '(UTC+11:00) Pohnpei' },
        { id : 'Asia/Sakhalin', name : '(UTC+11:00) Sakhalin' },
        { id : 'Pacific/Guadalcanal', name : '(UTC+11:00) Guadalcanal' },
        { id : 'Pacific/Efate', name : '(UTC+11:00) Efate' },
        { id : 'Asia/Anadyr', name : '(UTC+12:00) Anadyr' },
        { id : 'Pacific/Fiji', name : '(UTC+12:00) Fiji' },
        { id : 'Pacific/Tarawa', name : '(UTC+12:00) Tarawa' },
        { id : 'Pacific/Kwajalein', name : '(UTC+12:00) Kwajalein' },
        { id : 'Pacific/Majuro', name : '(UTC+12:00) Majuro' },
        { id : 'Pacific/Nauru', name : '(UTC+12:00) Nauru' },
        { id : 'Pacific/Auckland', name : '(UTC+12:00) Auckland' },
        { id : 'Antarctica/McMurdo', name : '(UTC+12:00) McMurdo' },
        { id : 'Asia/Kamchatka', name : '(UTC+12:00) Kamchatka' },
        { id : 'Pacific/Funafuti', name : '(UTC+12:00) Funafuti' },
        { id : 'Pacific/Wake', name : '(UTC+12:00) Wake' },
        { id : 'Pacific/Wallis', name : '(UTC+12:00) Wallis' },
        { id : 'Pacific/Chatham', name : '(UTC+12:45) Chatham' },
        { id : 'Pacific/Apia', name : '(UTC+13:00) Apia' },
        { id : 'Pacific/Kanton', name : '(UTC+13:00) Kanton' },
        { id : 'Pacific/Fakaofo', name : '(UTC+13:00) Fakaofo' },
        { id : 'Pacific/Tongatapu', name : '(UTC+13:00) Tongatapu' },
        { id : 'Pacific/Kiritimati', name : '(UTC+14:00) Kiritimati' }
    ];
}

module.exports.currencies = function(){
    return [
        { currency_code: 'AED', name: 'United Arab Emirates Dirham' },
        { currency_code: 'AFN', name: 'Afghan Afghani' },
        { currency_code: 'ALL', name: 'Albanian Lek' },
        { currency_code: 'AMD', name: 'Armenian Dram' },
        { currency_code: 'ANG', name: 'Netherlands Antillean Guilder' },
        { currency_code: 'AOA', name: 'Angolan Kwanza' },
        { currency_code: 'ARS', name: 'Argentine Peso' },
        { currency_code: 'AUD', name: 'Australian Dollar' },
        { currency_code: 'AWG', name: 'Aruban Florin' },
        { currency_code: 'AZN', name: 'Azerbaijani Manat' },
        { currency_code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark' },
        { currency_code: 'BBD', name: 'Barbadian Dollar' },
        { currency_code: 'BDT', name: 'Bangladeshi Taka' },
        { currency_code: 'BGN', name: 'Bulgarian Lev' },
        { currency_code: 'BHD', name: 'Bahraini Dinar' },
        { currency_code: 'BIF', name: 'Burundian Franc' },
        { currency_code: 'BMD', name: 'Bermudan Dollar' },
        { currency_code: 'BND', name: 'Brunei Dollar' },
        { currency_code: 'BOB', name: 'Bolivian Boliviano' },
        { currency_code: 'BRL', name: 'Brazilian Real' },
        { currency_code: 'BSD', name: 'Bahamian Dollar' },
        { currency_code: 'BTC', name: 'Bitcoin' },
        { currency_code: 'BTN', name: 'Bhutanese Ngultrum' },
        { currency_code: 'BWP', name: 'Botswanan Pula' },
        { currency_code: 'BYN', name: 'Belarusian Ruble' },
        { currency_code: 'BZD', name: 'Belize Dollar' },
        { currency_code: 'CAD', name: 'Canadian Dollar' },
        { currency_code: 'CDF', name: 'Congolese Franc' },
        { currency_code: 'CHF', name: 'Swiss Franc' },
        { currency_code: 'CLF', name: 'Chilean Unit of Account (UF)' },
        { currency_code: 'CLP', name: 'Chilean Peso' },
        { currency_code: 'CNH', name: 'Chinese Yuan (Offshore)' },
        { currency_code: 'CNY', name: 'Chinese Yuan' },
        { currency_code: 'COP', name: 'Colombian Peso' },
        { currency_code: 'CRC', name: 'Costa Rican Colón' },
        { currency_code: 'CUC', name: 'Cuban Convertible Peso' },
        { currency_code: 'CUP', name: 'Cuban Peso' },
        { currency_code: 'CVE', name: 'Cape Verdean Escudo' },
        { currency_code: 'CZK', name: 'Czech Republic Koruna' },
        { currency_code: 'DJF', name: 'Djiboutian Franc' },
        { currency_code: 'DKK', name: 'Danish Krone' },
        { currency_code: 'DOP', name: 'Dominican Peso' },
        { currency_code: 'DZD', name: 'Algerian Dinar' },
        { currency_code: 'EGP', name: 'Egyptian Pound' },
        { currency_code: 'ERN', name: 'Eritrean Nakfa' },
        { currency_code: 'ETB', name: 'Ethiopian Birr' },
        { currency_code: 'EUR', name: 'Euro' },
        { currency_code: 'FJD', name: 'Fijian Dollar' },
        { currency_code: 'FKP', name: 'Falkland Islands Pound' },
        { currency_code: 'GBP', name: 'British Pound Sterling' },
        { currency_code: 'GEL', name: 'Georgian Lari' },
        { currency_code: 'GGP', name: 'Guernsey Pound' },
        { currency_code: 'GHS', name: 'Ghanaian Cedi' },
        { currency_code: 'GIP', name: 'Gibraltar Pound' },
        { currency_code: 'GMD', name: 'Gambian Dalasi' },
        { currency_code: 'GNF', name: 'Guinean Franc' },
        { currency_code: 'GTQ', name: 'Guatemalan Quetzal' },
        { currency_code: 'GYD', name: 'Guyanaese Dollar' },
        { currency_code: 'HKD', name: 'Hong Kong Dollar' },
        { currency_code: 'HNL', name: 'Honduran Lempira' },
        { currency_code: 'HRK', name: 'Croatian Kuna' },
        { currency_code: 'HTG', name: 'Haitian Gourde' },
        { currency_code: 'HUF', name: 'Hungarian Forint' },
        { currency_code: 'IDR', name: 'Indonesian Rupiah' },
        { currency_code: 'ILS', name: 'Israeli New Sheqel' },
        { currency_code: 'IMP', name: 'Manx pound' },
        { currency_code: 'INR', name: 'Indian Rupee' },
        { currency_code: 'IQD', name: 'Iraqi Dinar' },
        { currency_code: 'IRR', name: 'Iranian Rial' },
        { currency_code: 'ISK', name: 'Icelandic Króna' },
        { currency_code: 'JEP', name: 'Jersey Pound' },
        { currency_code: 'JMD', name: 'Jamaican Dollar' },
        { currency_code: 'JOD', name: 'Jordanian Dinar' },
        { currency_code: 'JPY', name: 'Japanese Yen' },
        { currency_code: 'KES', name: 'Kenyan Shilling' },
        { currency_code: 'KGS', name: 'Kyrgystani Som' },
        { currency_code: 'KHR', name: 'Cambodian Riel' },
        { currency_code: 'KMF', name: 'Comorian Franc' },
        { currency_code: 'KPW', name: 'North Korean Won' },
        { currency_code: 'KRW', name: 'South Korean Won' },
        { currency_code: 'KWD', name: 'Kuwaiti Dinar' },
        { currency_code: 'KYD', name: 'Cayman Islands Dollar' },
        { currency_code: 'KZT', name: 'Kazakhstani Tenge' },
        { currency_code: 'LAK', name: 'Laotian Kip' },
        { currency_code: 'LBP', name: 'Lebanese Pound' },
        { currency_code: 'LKR', name: 'Sri Lankan Rupee' },
        { currency_code: 'LRD', name: 'Liberian Dollar' },
        { currency_code: 'LSL', name: 'Lesotho Loti' },
        { currency_code: 'LYD', name: 'Libyan Dinar' },
        { currency_code: 'MAD', name: 'Moroccan Dirham' },
        { currency_code: 'MDL', name: 'Moldovan Leu' },
        { currency_code: 'MGA', name: 'Malagasy Ariary' },
        { currency_code: 'MKD', name: 'Macedonian Denar' },
        { currency_code: 'MMK', name: 'Myanma Kyat' },
        { currency_code: 'MNT', name: 'Mongolian Tugrik' },
        { currency_code: 'MOP', name: 'Macanese Pataca' },
        { currency_code: 'MRU', name: 'Mauritanian Ouguiya' },
        { currency_code: 'MUR', name: 'Mauritian Rupee' },
        { currency_code: 'MVR', name: 'Maldivian Rufiyaa' },
        { currency_code: 'MWK', name: 'Malawian Kwacha' },
        { currency_code: 'MXN', name: 'Mexican Peso' },
        { currency_code: 'MYR', name: 'Malaysian Ringgit' },
        { currency_code: 'MZN', name: 'Mozambican Metical' },
        { currency_code: 'NAD', name: 'Namibian Dollar' },
        { currency_code: 'NGN', name: 'Nigerian Naira' },
        { currency_code: 'NIO', name: 'Nicaraguan Córdoba' },
        { currency_code: 'NOK', name: 'Norwegian Krone' },
        { currency_code: 'NPR', name: 'Nepalese Rupee' },
        { currency_code: 'NZD', name: 'New Zealand Dollar' },
        { currency_code: 'OMR', name: 'Omani Rial' },
        { currency_code: 'PAB', name: 'Panamanian Balboa' },
        { currency_code: 'PEN', name: 'Peruvian Nuevo Sol' },
        { currency_code: 'PGK', name: 'Papua New Guinean Kina' },
        { currency_code: 'PHP', name: 'Philippine Peso' },
        { currency_code: 'PKR', name: 'Pakistani Rupee' },
        { currency_code: 'PLN', name: 'Polish Zloty' },
        { currency_code: 'PYG', name: 'Paraguayan Guarani' },
        { currency_code: 'QAR', name: 'Qatari Rial' },
        { currency_code: 'RON', name: 'Romanian Leu' },
        { currency_code: 'RSD', name: 'Serbian Dinar' },
        { currency_code: 'RUB', name: 'Russian Ruble' },
        { currency_code: 'RWF', name: 'Rwandan Franc' },
        { currency_code: 'SAR', name: 'Saudi Riyal' },
        { currency_code: 'SBD', name: 'Solomon Islands Dollar' },
        { currency_code: 'SCR', name: 'Seychellois Rupee' },
        { currency_code: 'SDG', name: 'Sudanese Pound' },
        { currency_code: 'SEK', name: 'Swedish Krona' },
        { currency_code: 'SGD', name: 'Singapore Dollar' },
        { currency_code: 'SHP', name: 'Saint Helena Pound' },
        { currency_code: 'SLL', name: 'Sierra Leonean Leone' },
        { currency_code: 'SOS', name: 'Somali Shilling' },
        { currency_code: 'SRD', name: 'Surinamese Dollar' },
        { currency_code: 'SSP', name: 'South Sudanese Pound' },
        { currency_code: 'STN', name: 'São Tomé and Príncipe Dobra' },
        { currency_code: 'SVC', name: 'Salvadoran Colón' },
        { currency_code: 'SYP', name: 'Syrian Pound' },
        { currency_code: 'SZL', name: 'Swazi Lilangeni' },
        { currency_code: 'THB', name: 'Thai Baht' },
        { currency_code: 'TJS', name: 'Tajikistani Somoni' },
        { currency_code: 'TMT', name: 'Turkmenistani Manat' },
        { currency_code: 'TND', name: 'Tunisian Dinar' },
        { currency_code: 'TOP', name: "Tongan Pa'anga" },
        { currency_code: 'TRY', name: 'Turkish Lira' },
        { currency_code: 'TTD', name: 'Trinidad and Tobago Dollar' },
        { currency_code: 'TWD', name: 'New Taiwan Dollar' },
        { currency_code: 'TZS', name: 'Tanzanian Shilling' },
        { currency_code: 'UAH', name: 'Ukrainian Hryvnia' },
        { currency_code: 'UGX', name: 'Ugandan Shilling' },
        { currency_code: 'USD', name: 'United States Dollar' },
        { currency_code: 'UYU', name: 'Uruguayan Peso' },
        { currency_code: 'UZS', name: 'Uzbekistan Som' },
        { currency_code: 'VES', name: 'Venezuelan Bolívar Soberano' },
        { currency_code: 'VND', name: 'Vietnamese Dong' },
        { currency_code: 'VUV', name: 'Vanuatu Vatu' },
        { currency_code: 'WST', name: 'Samoan Tala' },
        { currency_code: 'XAF', name: 'CFA Franc BEAC' },
        { currency_code: 'XAG', name: 'Silver Ounce' },
        { currency_code: 'XAU', name: 'Gold Ounce' },
        { currency_code: 'XCD', name: 'East Caribbean Dollar' },
        { currency_code: 'XDR', name: 'Special Drawing Rights' },
        { currency_code: 'XOF', name: 'CFA Franc BCEAO' },
        { currency_code: 'XPD', name: 'Palladium Ounce' },
        { currency_code: 'XPF', name: 'CFP Franc' },
        { currency_code: 'XPT', name: 'Platinum Ounce' },
        { currency_code: 'YER', name: 'Yemeni Rial' },
        { currency_code: 'ZAR', name: 'South African Rand' },
        { currency_code: 'ZMW', name: 'Zambian Kwacha' },
        { currency_code: 'ZWL', name: 'Zimbabwean Dollar' }
    ];
};